version: '3.1'

services:

  mongo:
    image: mongo:6.0.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cronos_app
      MONGO_INITDB_ROOT_PASSWORD: S3cret!
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cronos_app
      ME_CONFIG_MONGODB_ADMINPASSWORD: S3cret!
      ME_CONFIG_MONGODB_URL: mongodb://cronos_app:S3cret!@mongo:27017/
    depends_on:
      - mongo

volumes:
   mongodb-data:
