/* tslint:disable */
/* eslint-disable */
/**
 * Cronos-Med
 * All request used by Cronos Med app
 *
 * OpenAPI spec version: 1.0
 * Contact: mariocabral.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProfesionalResponse } from './profesional-response';
/**
 * 
 * @export
 * @interface ProfesionalListResponse
 */
export interface ProfesionalListResponse extends Array<ProfesionalResponse> {
}
