/* tslint:disable */
/* eslint-disable */
/**
 * Cronos-Med
 * All request used by Cronos Med app
 *
 * OpenAPI spec version: 1.0
 * Contact: mariocabral.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProfesionalRequest
 */
export interface ProfesionalRequest {
    /**
     * 
     * @type {string}
     * @memberof ProfesionalRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfesionalRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfesionalRequest
     */
    licence: string;
    /**
     * 
     * @type {string}
     * @memberof ProfesionalRequest
     */
    degree: string;
    /**
     * 
     * @type {string}
     * @memberof ProfesionalRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ProfesionalRequest
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProfesionalRequest
     */
    phones: Array<string>;
    /**
     * The date that the user was created.
     * @type {string}
     * @memberof ProfesionalRequest
     */
    createDate?: string;
    /**
     * The last date that the user was updated.
     * @type {string}
     * @memberof ProfesionalRequest
     */
    lastModificationDate?: string;
}
