/* tslint:disable */
/* eslint-disable */
/**
 * Cronos-Med
 * All request used by Cronos Med app
 *
 * OpenAPI spec version: 1.0
 * Contact: mariocabral.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RoomResponse
 */
export interface RoomResponse {
    /**
     * Unique identifier for the given user.
     * @type {string}
     * @memberof RoomResponse
     */
    roomId: string;
    /**
     * 
     * @type {string}
     * @memberof RoomResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoomResponse
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof RoomResponse
     */
    enabled: boolean;
    /**
     * The date that the user was created.
     * @type {string}
     * @memberof RoomResponse
     */
    createDate: string;
    /**
     * The last date that the user was updated.
     * @type {string}
     * @memberof RoomResponse
     */
    lastModificationDate?: string;
}
